import type { Metadata } from 'next';

import Footer from '@/components/common/footer';
import Header from '@/components/common/header';

import '@/css/globals.css';
import '@/css/prism.css';

export const metadata: Metadata = {
  title: 'ByteHopper Blog',
  description: 'Generated by ByteHopper',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
